### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Katolus** [Katolus/functions#175]
### What happened?

A bug happened!

### Steps To Reproduce

dsad

### Version

0.1.0

### Contact Details

My @ams

### Environment

```markdown
- OS:
- Python:
- Docker:
- Poetry:
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ams** [comment]
Contact Details

   My @ams

I think you typoed something.
